### ISSUE TITLE
iOS 网页隐藏滚动条

### ISSUE THREAD

**Issue by ourongxing** [ourongxing/solve-the-problem#29]
```css
html::-webkit-scrollbar,
body::-webkit-scrollbar {
    display: none;
}

html,
body {
    height: 100%;
    overflow: hidden;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
}
```
